name: jawara
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  stacked: ^1.7.6
  provider: ^4.3.2+2

  # Services
  stacked_services: ^0.5.2
  get_it: ^4.0.4

  # Inversion of Control
  injectable: ^1.0.4

  # Helper
  image_picker: ^0.6.7+12

  # UI
  cupertino_icons: ^1.0.0
  get: ^3.4.6
  flutter_screenutil: ^3.1.1
  google_fonts: ^1.1.0
  material_design_icons_flutter: ^4.0.5755
  simple_animations: ^2.2.3
  steps_indicator: ^1.1.0
  page_slider: ^0.0.2

  # Network
  connectivity: ^0.4.9+3
  cached_network_image: ^2.2.0+1
  dio: ^3.0.10
  retrofit: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  auto_route_generator: ^0.6.7
  injectable_generator: ^1.0.4
  build_resolvers: ^1.3.11
  retrofit_generator: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700